### ISSUE TITLE
compile error at 91%

### ISSUE THREAD

**Issue by VR2XKP** [mobilinkd/m17-cxx-demod#14]
while  I proceed "make" command, it shows error on 91% as follow: 

[ 91%] Building CXX object tests/CMakeFiles/SlidingDFTTest.dir/SlidingDFTTest.cpp.o
/home/pi/m17-cxx-demod-master/tests/SlidingDFTTest.cpp: In member function 'virtual void SlidingDFTTest_dft_3000hz_square_Test::TestBody()':
/home/pi/m17-cxx-demod-master/tests/SlidingDFTTest.cpp:35:83: error: 'ref' is not a member of 'std'
auto it = std::transform(input.begin(), input.end(), result.begin(), std::ref(dft));
^~~

any hints to solve it

**Comment by jketterl** [comment]
That looks exactly like the error I had today, there's a proposed fix in #13 if you would like to experiment.

**Comment by mobilinkd** [comment]
I think this is fixed with 9672a90e7128db5b1b29872670ab0c14be777f72
