### ISSUE TITLE
New tag or a release, please?

### ISSUE THREAD

**Issue by n1ai** [mobilinkd/m17-cxx-demod#15]
Hi, Rob.

I'm attempting to package m17-cxx-demod under conda for a few different reasons.

This would be easier if you could create a new tag since the last one v2.2 seems to be from July and there seem to be good fixes since then.

Conda seems to have a slight preference for releases over tags, so if you were planning to make a release that would be good too.

In the mean time I could put a tag on my fork of this repo but I have no intent/desire to maintain a fork.

Regards,
Dave, N1AI

**Comment by mobilinkd** [comment]
Thanks.  Tag v2.3 added.
